// Code generated by golex. DO NOT EDIT.

package main

// Copyright (c) 2011 CZ.NIC z.s.p.o. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// blame: jnml, labs.nic.cz

// +build ignore

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"unicode"
	"unicode/utf8"
)

var (
	src     []byte
	srclen  int
	pos     int
	pos0    int
	line    int
	column  int
	current byte
	sc      int
)

const (
	SEP = 0xE000 + iota
	PUNCT
	KWD
	IDENT
	STRING
	CHAR
	INT
	FLOAT
	IMAG
)

func getc() byte {
	pos++
	if pos >= srclen {
		current = 0
		return 0
	}

	current = src[pos]
	if current == '\n' {
		line++
		column = 1
	} else {
		column++
	}
	return current
}

func begin(cond int) {
	sc = cond
}

func getRune() rune {
	if rune, size := utf8.DecodeRune(src[pos:]); size != 0 {
		pos += size
		return rune
	}

	return 0
}

func scan() (x int) {
	const (
		INITIAL = iota
		QSTR
		CH
	)

	c := current

yystate0:

	pos0 = pos

	switch yyt := sc; yyt {
	default:
		panic(fmt.Errorf(`invalid start condition %d`, yyt))
	case 0: // start condition: INITIAL
		goto yystart1
	case 1: // start condition: QSTR
		goto yystart188
	case 2: // start condition: CH
		goto yystart205
	}

	goto yystate0 // silence unused label error
	goto yystate1 // silence unused label error
yystate1:
	c = getc()
yystart1:
	switch {
	default:
		goto yyabort
	case c == '!':
		goto yystate4
	case c == '"':
		goto yystate6
	case c == '%':
		goto yystate7
	case c == '&':
		goto yystate9
	case c == '(':
		goto yystate15
	case c == ')':
		goto yystate16
	case c == '*':
		goto yystate17
	case c == '+':
		goto yystate19
	case c == ',':
		goto yystate22
	case c == '-':
		goto yystate23
	case c == '.':
		goto yystate26
	case c == '/':
		goto yystate34
	case c == '0':
		goto yystate40
	case c == ':':
		goto yystate46
	case c == ';':
		goto yystate48
	case c == '<':
		goto yystate49
	case c == '=':
		goto yystate54
	case c == '>':
		goto yystate56
	case c == '[':
		goto yystate61
	case c == '\'':
		goto yystate14
	case c == '\t' || c == '\n' || c == '\r' || c == ' ':
		goto yystate3
	case c == '\x00':
		goto yystate2
	case c == ']':
		goto yystate62
	case c == '^':
		goto yystate63
	case c == '`':
		goto yystate65
	case c == 'b':
		goto yystate67
	case c == 'c':
		goto yystate72
	case c == 'd':
		goto yystate88
	case c == 'e':
		goto yystate97
	case c == 'f':
		goto yystate101
	case c == 'g':
		goto yystate117
	case c == 'i':
		goto yystate121
	case c == 'm':
		goto yystate136
	case c == 'p':
		goto yystate139
	case c == 'r':
		goto yystate146
	case c == 's':
		goto yystate156
	case c == 't':
		goto yystate172
	case c == 'v':
		goto yystate176
	case c == '{':
		goto yystate179
	case c == '|':
		goto yystate180
	case c == '}':
		goto yystate183
	case c >= '1' && c <= '9':
		goto yystate45
	case c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'h' || c >= 'j' && c <= 'l' || c == 'n' || c == 'o' || c == 'q' || c == 'u' || c >= 'w' && c <= 'z':
		goto yystate60
	case c >= 'Â' && c <= 'ß':
		goto yystate184
	case c >= 'à' && c <= 'ï':
		goto yystate186
	case c >= 'ð' && c <= 'ô':
		goto yystate187
	}

yystate2:
	c = getc()
	goto yyrule1

yystate3:
	c = getc()
	switch {
	default:
		goto yyrule2
	case c == '\t' || c == '\n' || c == '\r' || c == ' ':
		goto yystate3
	}

yystate4:
	c = getc()
	switch {
	default:
		goto yyrule36
	case c == '=':
		goto yystate5
	}

yystate5:
	c = getc()
	goto yyrule37

yystate6:
	c = getc()
	goto yyrule77

yystate7:
	c = getc()
	switch {
	default:
		goto yyrule9
	case c == '=':
		goto yystate8
	}

yystate8:
	c = getc()
	goto yyrule20

yystate9:
	c = getc()
	switch {
	default:
		goto yyrule10
	case c == '&':
		goto yystate10
	case c == '=':
		goto yystate11
	case c == '^':
		goto yystate12
	}

yystate10:
	c = getc()
	goto yyrule27

yystate11:
	c = getc()
	goto yyrule21

yystate12:
	c = getc()
	switch {
	default:
		goto yyrule15
	case c == '=':
		goto yystate13
	}

yystate13:
	c = getc()
	goto yyrule26

yystate14:
	c = getc()
	goto yyrule80

yystate15:
	c = getc()
	goto yyrule42

yystate16:
	c = getc()
	goto yyrule47

yystate17:
	c = getc()
	switch {
	default:
		goto yyrule7
	case c == '=':
		goto yystate18
	}

yystate18:
	c = getc()
	goto yyrule18

yystate19:
	c = getc()
	switch {
	default:
		goto yyrule5
	case c == '+':
		goto yystate20
	case c == '=':
		goto yystate21
	}

yystate20:
	c = getc()
	goto yyrule30

yystate21:
	c = getc()
	goto yyrule16

yystate22:
	c = getc()
	goto yyrule45

yystate23:
	c = getc()
	switch {
	default:
		goto yyrule6
	case c == '-':
		goto yystate24
	case c == '=':
		goto yystate25
	}

yystate24:
	c = getc()
	goto yyrule31

yystate25:
	c = getc()
	goto yyrule17

yystate26:
	c = getc()
	switch {
	default:
		goto yyrule46
	case c == '.':
		goto yystate27
	case c >= '0' && c <= '9':
		goto yystate29
	}

yystate27:
	c = getc()
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate28
	}

yystate28:
	c = getc()
	goto yyrule41

yystate29:
	c = getc()
	switch {
	default:
		goto yyrule83
	case c == 'E' || c == 'e':
		goto yystate30
	case c == 'i':
		goto yystate33
	case c >= '0' && c <= '9':
		goto yystate29
	}

yystate30:
	c = getc()
	switch {
	default:
		goto yyabort
	case c == '+' || c == '-':
		goto yystate31
	case c >= '0' && c <= '9':
		goto yystate32
	}

yystate31:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate32
	}

yystate32:
	c = getc()
	switch {
	default:
		goto yyrule83
	case c == 'i':
		goto yystate33
	case c >= '0' && c <= '9':
		goto yystate32
	}

yystate33:
	c = getc()
	goto yyrule84

yystate34:
	c = getc()
	switch {
	default:
		goto yyrule8
	case c == '*':
		goto yystate35
	case c == '/':
		goto yystate38
	case c == '=':
		goto yystate39
	}

yystate35:
	c = getc()
	switch {
	default:
		goto yyabort
	case c == '*':
		goto yystate36
	case c >= '\x01' && c <= ')' || c >= '+' && c <= 'ÿ':
		goto yystate35
	}

yystate36:
	c = getc()
	switch {
	default:
		goto yyabort
	case c == '*':
		goto yystate36
	case c == '/':
		goto yystate37
	case c >= '\x01' && c <= ')' || c >= '+' && c <= '.' || c >= '0' && c <= 'ÿ':
		goto yystate35
	}

yystate37:
	c = getc()
	goto yyrule4

yystate38:
	c = getc()
	switch {
	default:
		goto yyrule3
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate38
	}

yystate39:
	c = getc()
	goto yyrule19

yystate40:
	c = getc()
	switch {
	default:
		goto yyrule82
	case c == '.':
		goto yystate29
	case c == '8' || c == '9':
		goto yystate42
	case c == 'E' || c == 'e':
		goto yystate30
	case c == 'X' || c == 'x':
		goto yystate43
	case c == 'i':
		goto yystate33
	case c >= '0' && c <= '7':
		goto yystate41
	}

yystate41:
	c = getc()
	switch {
	default:
		goto yyrule82
	case c == '.':
		goto yystate29
	case c == '8' || c == '9':
		goto yystate42
	case c == 'E' || c == 'e':
		goto yystate30
	case c == 'i':
		goto yystate33
	case c >= '0' && c <= '7':
		goto yystate41
	}

yystate42:
	c = getc()
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate29
	case c == 'E' || c == 'e':
		goto yystate30
	case c == 'i':
		goto yystate33
	case c >= '0' && c <= '9':
		goto yystate42
	}

yystate43:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate44
	}

yystate44:
	c = getc()
	switch {
	default:
		goto yyrule82
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate44
	}

yystate45:
	c = getc()
	switch {
	default:
		goto yyrule82
	case c == '.':
		goto yystate29
	case c == 'E' || c == 'e':
		goto yystate30
	case c == 'i':
		goto yystate33
	case c >= '0' && c <= '9':
		goto yystate45
	}

yystate46:
	c = getc()
	switch {
	default:
		goto yyrule51
	case c == '=':
		goto yystate47
	}

yystate47:
	c = getc()
	goto yyrule40

yystate48:
	c = getc()
	goto yyrule50

yystate49:
	c = getc()
	switch {
	default:
		goto yyrule33
	case c == '-':
		goto yystate50
	case c == '<':
		goto yystate51
	case c == '=':
		goto yystate53
	}

yystate50:
	c = getc()
	goto yyrule29

yystate51:
	c = getc()
	switch {
	default:
		goto yyrule13
	case c == '=':
		goto yystate52
	}

yystate52:
	c = getc()
	goto yyrule24

yystate53:
	c = getc()
	goto yyrule38

yystate54:
	c = getc()
	switch {
	default:
		goto yyrule35
	case c == '=':
		goto yystate55
	}

yystate55:
	c = getc()
	goto yyrule32

yystate56:
	c = getc()
	switch {
	default:
		goto yyrule34
	case c == '=':
		goto yystate57
	case c == '>':
		goto yystate58
	}

yystate57:
	c = getc()
	goto yyrule39

yystate58:
	c = getc()
	switch {
	default:
		goto yyrule14
	case c == '=':
		goto yystate59
	}

yystate59:
	c = getc()
	goto yyrule25

yystate60:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate61:
	c = getc()
	goto yyrule43

yystate62:
	c = getc()
	goto yyrule48

yystate63:
	c = getc()
	switch {
	default:
		goto yyrule12
	case c == '=':
		goto yystate64
	}

yystate64:
	c = getc()
	goto yyrule23

yystate65:
	c = getc()
	switch {
	default:
		goto yyabort
	case c == '`':
		goto yystate66
	case c >= '\x01' && c <= '_' || c >= 'a' && c <= 'ÿ':
		goto yystate65
	}

yystate66:
	c = getc()
	goto yyrule79

yystate67:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'r':
		goto yystate68
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate60
	}

yystate68:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'e':
		goto yystate69
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate69:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'a':
		goto yystate70
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate60
	}

yystate70:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'k':
		goto yystate71
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z':
		goto yystate60
	}

yystate71:
	c = getc()
	switch {
	default:
		goto yyrule52
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate72:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'a':
		goto yystate73
	case c == 'h':
		goto yystate76
	case c == 'o':
		goto yystate79
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'g' || c >= 'i' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate60
	}

yystate73:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 's':
		goto yystate74
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z':
		goto yystate60
	}

yystate74:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'e':
		goto yystate75
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate75:
	c = getc()
	switch {
	default:
		goto yyrule53
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate76:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'a':
		goto yystate77
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate60
	}

yystate77:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'n':
		goto yystate78
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate60
	}

yystate78:
	c = getc()
	switch {
	default:
		goto yyrule54
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate79:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'n':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate60
	}

yystate80:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 's':
		goto yystate81
	case c == 't':
		goto yystate83
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 'u' && c <= 'z':
		goto yystate60
	}

yystate81:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 't':
		goto yystate82
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate60
	}

yystate82:
	c = getc()
	switch {
	default:
		goto yyrule55
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate83:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'i':
		goto yystate84
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate60
	}

yystate84:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'n':
		goto yystate85
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate60
	}

yystate85:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'u':
		goto yystate86
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z':
		goto yystate60
	}

yystate86:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'e':
		goto yystate87
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate87:
	c = getc()
	switch {
	default:
		goto yyrule56
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate88:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'e':
		goto yystate89
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate89:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'f':
		goto yystate90
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'e' || c >= 'g' && c <= 'z':
		goto yystate60
	}

yystate90:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'a':
		goto yystate91
	case c == 'e':
		goto yystate95
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate91:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'u':
		goto yystate92
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z':
		goto yystate60
	}

yystate92:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'l':
		goto yystate93
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate60
	}

yystate93:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 't':
		goto yystate94
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate60
	}

yystate94:
	c = getc()
	switch {
	default:
		goto yyrule57
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate95:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'r':
		goto yystate96
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate60
	}

yystate96:
	c = getc()
	switch {
	default:
		goto yyrule58
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate97:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'l':
		goto yystate98
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate60
	}

yystate98:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 's':
		goto yystate99
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z':
		goto yystate60
	}

yystate99:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'e':
		goto yystate100
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate100:
	c = getc()
	switch {
	default:
		goto yyrule59
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate101:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'a':
		goto yystate102
	case c == 'o':
		goto yystate112
	case c == 'u':
		goto yystate114
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'n' || c >= 'p' && c <= 't' || c >= 'v' && c <= 'z':
		goto yystate60
	}

yystate102:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'l':
		goto yystate103
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate60
	}

yystate103:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'l':
		goto yystate104
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate60
	}

yystate104:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 't':
		goto yystate105
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate60
	}

yystate105:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'h':
		goto yystate106
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'g' || c >= 'i' && c <= 'z':
		goto yystate60
	}

yystate106:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'r':
		goto yystate107
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate60
	}

yystate107:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'o':
		goto yystate108
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate60
	}

yystate108:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'u':
		goto yystate109
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z':
		goto yystate60
	}

yystate109:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'g':
		goto yystate110
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'f' || c >= 'h' && c <= 'z':
		goto yystate60
	}

yystate110:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'h':
		goto yystate111
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'g' || c >= 'i' && c <= 'z':
		goto yystate60
	}

yystate111:
	c = getc()
	switch {
	default:
		goto yyrule60
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate112:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'r':
		goto yystate113
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate60
	}

yystate113:
	c = getc()
	switch {
	default:
		goto yyrule61
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate114:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'n':
		goto yystate115
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate60
	}

yystate115:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'c':
		goto yystate116
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z':
		goto yystate60
	}

yystate116:
	c = getc()
	switch {
	default:
		goto yyrule62
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate117:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'o':
		goto yystate118
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate60
	}

yystate118:
	c = getc()
	switch {
	default:
		goto yyrule63
	case c == 't':
		goto yystate119
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate60
	}

yystate119:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'o':
		goto yystate120
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate60
	}

yystate120:
	c = getc()
	switch {
	default:
		goto yyrule64
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate121:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'f':
		goto yystate122
	case c == 'm':
		goto yystate123
	case c == 'n':
		goto yystate128
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'e' || c >= 'g' && c <= 'l' || c >= 'o' && c <= 'z':
		goto yystate60
	}

yystate122:
	c = getc()
	switch {
	default:
		goto yyrule65
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate123:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'p':
		goto yystate124
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z':
		goto yystate60
	}

yystate124:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'o':
		goto yystate125
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate60
	}

yystate125:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'r':
		goto yystate126
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate60
	}

yystate126:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 't':
		goto yystate127
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate60
	}

yystate127:
	c = getc()
	switch {
	default:
		goto yyrule66
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate128:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 't':
		goto yystate129
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate60
	}

yystate129:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'e':
		goto yystate130
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate130:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'r':
		goto yystate131
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate60
	}

yystate131:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'f':
		goto yystate132
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'e' || c >= 'g' && c <= 'z':
		goto yystate60
	}

yystate132:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'a':
		goto yystate133
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate60
	}

yystate133:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'c':
		goto yystate134
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z':
		goto yystate60
	}

yystate134:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'e':
		goto yystate135
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate135:
	c = getc()
	switch {
	default:
		goto yyrule67
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate136:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'a':
		goto yystate137
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate60
	}

yystate137:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'p':
		goto yystate138
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z':
		goto yystate60
	}

yystate138:
	c = getc()
	switch {
	default:
		goto yyrule68
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate139:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'a':
		goto yystate140
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate60
	}

yystate140:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'c':
		goto yystate141
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z':
		goto yystate60
	}

yystate141:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'k':
		goto yystate142
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z':
		goto yystate60
	}

yystate142:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'a':
		goto yystate143
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate60
	}

yystate143:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'g':
		goto yystate144
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'f' || c >= 'h' && c <= 'z':
		goto yystate60
	}

yystate144:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'e':
		goto yystate145
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate145:
	c = getc()
	switch {
	default:
		goto yyrule69
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate146:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'a':
		goto yystate147
	case c == 'e':
		goto yystate151
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate147:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'n':
		goto yystate148
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate60
	}

yystate148:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'g':
		goto yystate149
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'f' || c >= 'h' && c <= 'z':
		goto yystate60
	}

yystate149:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'e':
		goto yystate150
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate150:
	c = getc()
	switch {
	default:
		goto yyrule70
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate151:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 't':
		goto yystate152
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate60
	}

yystate152:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'u':
		goto yystate153
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z':
		goto yystate60
	}

yystate153:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'r':
		goto yystate154
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate60
	}

yystate154:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'n':
		goto yystate155
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate60
	}

yystate155:
	c = getc()
	switch {
	default:
		goto yyrule71
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate156:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'e':
		goto yystate157
	case c == 't':
		goto yystate162
	case c == 'w':
		goto yystate167
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 's' || c == 'u' || c == 'v' || c >= 'x' && c <= 'z':
		goto yystate60
	}

yystate157:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'l':
		goto yystate158
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate60
	}

yystate158:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'e':
		goto yystate159
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate159:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'c':
		goto yystate160
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z':
		goto yystate60
	}

yystate160:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 't':
		goto yystate161
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate60
	}

yystate161:
	c = getc()
	switch {
	default:
		goto yyrule72
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate162:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'r':
		goto yystate163
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate60
	}

yystate163:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'u':
		goto yystate164
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z':
		goto yystate60
	}

yystate164:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'c':
		goto yystate165
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z':
		goto yystate60
	}

yystate165:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 't':
		goto yystate166
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate60
	}

yystate166:
	c = getc()
	switch {
	default:
		goto yyrule73
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate167:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'i':
		goto yystate168
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate60
	}

yystate168:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 't':
		goto yystate169
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate60
	}

yystate169:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'c':
		goto yystate170
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z':
		goto yystate60
	}

yystate170:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'h':
		goto yystate171
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'g' || c >= 'i' && c <= 'z':
		goto yystate60
	}

yystate171:
	c = getc()
	switch {
	default:
		goto yyrule74
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate172:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'y':
		goto yystate173
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'x' || c == 'z':
		goto yystate60
	}

yystate173:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'p':
		goto yystate174
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z':
		goto yystate60
	}

yystate174:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'e':
		goto yystate175
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate60
	}

yystate175:
	c = getc()
	switch {
	default:
		goto yyrule75
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate176:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'a':
		goto yystate177
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate60
	}

yystate177:
	c = getc()
	switch {
	default:
		goto yyrule85
	case c == 'r':
		goto yystate178
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate60
	}

yystate178:
	c = getc()
	switch {
	default:
		goto yyrule76
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate60
	}

yystate179:
	c = getc()
	goto yyrule44

yystate180:
	c = getc()
	switch {
	default:
		goto yyrule11
	case c == '=':
		goto yystate181
	case c == '|':
		goto yystate182
	}

yystate181:
	c = getc()
	goto yyrule22

yystate182:
	c = getc()
	goto yyrule28

yystate183:
	c = getc()
	goto yyrule49

yystate184:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '\u0080' && c <= '¿':
		goto yystate185
	}

yystate185:
	c = getc()
	goto yyrule86

yystate186:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '\u0080' && c <= '¿':
		goto yystate184
	}

yystate187:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '\u0080' && c <= '¿':
		goto yystate186
	}

	goto yystate188 // silence unused label error
yystate188:
	c = getc()
yystart188:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate190
	case c == '\\':
		goto yystate191
	case c == '\x00':
		goto yystate2
	case c >= '\x01' && c <= '\t' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '!' || c >= '#' && c <= '[' || c >= ']' && c <= '\u007f':
		goto yystate189
	case c >= 'Â' && c <= 'ß':
		goto yystate202
	case c >= 'à' && c <= 'ï':
		goto yystate203
	case c >= 'ð' && c <= 'ô':
		goto yystate204
	}

yystate189:
	c = getc()
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate190
	case c == '\\':
		goto yystate191
	case c >= '\x01' && c <= '\t' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '!' || c >= '#' && c <= '[' || c >= ']' && c <= '\u007f':
		goto yystate189
	case c >= 'Â' && c <= 'ß':
		goto yystate202
	case c >= 'à' && c <= 'ï':
		goto yystate203
	case c >= 'ð' && c <= 'ô':
		goto yystate204
	}

yystate190:
	c = getc()
	goto yyrule78

yystate191:
	c = getc()
	switch {
	default:
		goto yyabort
	case c == '"' || c == '\\' || c == 'a' || c == 'b' || c == 'f' || c == 'n' || c == 'r' || c == 't' || c == 'v':
		goto yystate189
	case c == 'U':
		goto yystate194
	case c == 'u':
		goto yystate198
	case c == 'x':
		goto yystate200
	case c >= '0' && c <= '7':
		goto yystate192
	}

yystate192:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '7':
		goto yystate193
	}

yystate193:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '7':
		goto yystate189
	}

yystate194:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate195
	}

yystate195:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate196
	}

yystate196:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate197
	}

yystate197:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate198
	}

yystate198:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate199
	}

yystate199:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate200
	}

yystate200:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate201
	}

yystate201:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate189
	}

yystate202:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '\u0080' && c <= '¿':
		goto yystate189
	}

yystate203:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '\u0080' && c <= '¿':
		goto yystate202
	}

yystate204:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '\u0080' && c <= '¿':
		goto yystate203
	}

	goto yystate205 // silence unused label error
yystate205:
	c = getc()
yystart205:
	switch {
	default:
		goto yyabort
	case c == '\\':
		goto yystate208
	case c == '\x00':
		goto yystate2
	case c >= '\x01' && c <= '\t' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '&' || c >= '(' && c <= '[' || c >= ']' && c <= '\u007f':
		goto yystate206
	case c >= 'Â' && c <= 'ß':
		goto yystate219
	case c >= 'à' && c <= 'ï':
		goto yystate220
	case c >= 'ð' && c <= 'ô':
		goto yystate221
	}

yystate206:
	c = getc()
	switch {
	default:
		goto yyabort
	case c == '\'':
		goto yystate207
	}

yystate207:
	c = getc()
	goto yyrule81

yystate208:
	c = getc()
	switch {
	default:
		goto yyabort
	case c == 'U':
		goto yystate211
	case c == '\'' || c == '\\' || c == 'a' || c == 'b' || c == 'f' || c == 'n' || c == 'r' || c == 't' || c == 'v':
		goto yystate206
	case c == 'u':
		goto yystate215
	case c == 'x':
		goto yystate217
	case c >= '0' && c <= '7':
		goto yystate209
	}

yystate209:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '7':
		goto yystate210
	}

yystate210:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '7':
		goto yystate206
	}

yystate211:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate212
	}

yystate212:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate213
	}

yystate213:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate214
	}

yystate214:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate215
	}

yystate215:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate216
	}

yystate216:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate217
	}

yystate217:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate218
	}

yystate218:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'a' && c <= 'f':
		goto yystate206
	}

yystate219:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '\u0080' && c <= '¿':
		goto yystate206
	}

yystate220:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '\u0080' && c <= '¿':
		goto yystate219
	}

yystate221:
	c = getc()
	switch {
	default:
		goto yyabort
	case c >= '\u0080' && c <= '¿':
		goto yystate220
	}

yyrule1: // \0
	{
		return 0
	}
yyrule2: // [ \t\n\r]+
yyrule3: // \/\/.*
yyrule4: // \/\*([^*]|\*+[^*/])*\*+\/

	goto yystate0
yyrule5: // "+"
yyrule6: // "-"
yyrule7: // "*"
yyrule8: // "/"
yyrule9: // "%"
yyrule10: // "&"
yyrule11: // "|"
yyrule12: // "^"
yyrule13: // "<<"
yyrule14: // ">>"
yyrule15: // "&^"
yyrule16: // "+="
yyrule17: // "-="
yyrule18: // "*="
yyrule19: // "/="
yyrule20: // "%="
yyrule21: // "&="
yyrule22: // "|="
yyrule23: // "^="
yyrule24: // "<<="
yyrule25: // ">>="
yyrule26: // "&^="
yyrule27: // "&&"
yyrule28: // "||"
yyrule29: // "<-"
yyrule30: // "++"
yyrule31: // "--"
yyrule32: // "=="
yyrule33: // "<"
yyrule34: // ">"
yyrule35: // "="
yyrule36: // "!"
yyrule37: // "!="
yyrule38: // "<="
yyrule39: // ">="
yyrule40: // ":="
yyrule41: // "..."
yyrule42: // "("
yyrule43: // "["
yyrule44: // "{"
yyrule45: // ","
yyrule46: // "."
yyrule47: // ")"
yyrule48: // "]"
yyrule49: // "}"
yyrule50: // ";"
yyrule51: // ":"
	{
		return PUNCT
	}
yyrule52: // break
yyrule53: // case
yyrule54: // chan
yyrule55: // const
yyrule56: // continue
yyrule57: // default
yyrule58: // defer
yyrule59: // else
yyrule60: // fallthrough
yyrule61: // for
yyrule62: // func
yyrule63: // go
yyrule64: // goto
yyrule65: // if
yyrule66: // import
yyrule67: // interface
yyrule68: // map
yyrule69: // package
yyrule70: // range
yyrule71: // return
yyrule72: // select
yyrule73: // struct
yyrule74: // switch
yyrule75: // type
yyrule76: // var
	{
		return KWD
	}
yyrule77: // \"
	{
		begin(QSTR)
		goto yystate0
	}
yyrule78: // {interpreted_string_lit}
	{

		begin(INITIAL)
		return STRING
	}
yyrule79: // `[^`]*`
	{
		return STRING
	}
yyrule80: // '
	{
		begin(CH)
		goto yystate0
	}
yyrule81: // ({char_unicode_value}|{byte_value})'
	{

		begin(INITIAL)
		return CHAR
	}
yyrule82: // {int_lit}
	{
		return INT
	}
yyrule83: // {float_lit}
	{
		return FLOAT
	}
yyrule84: // {imaginary_lit}
	{
		return IMAG
	}
yyrule85: // [a-zA-Z_][a-zA-Z_0-9]*
	{

		if current >= '\xC2' && current <= '\xF4' {
			pos--
			column--
			for {
				l, c, runepos := line, column, pos
				rune := getRune()
				if !(rune == '_' || unicode.IsLetter(rune) || unicode.IsDigit(rune)) {
					pos = runepos
					current = getc()
					line, column = l, c
					break
				}
			}
		}
		return IDENT
	}
yyrule86: // {non_ascii}
	{

		pos = pos0
		if rune := getRune(); !unicode.IsLetter(rune) {
			panic(fmt.Errorf("expected unicode letter, got %U", rune))
		}
		for {
			l, c, runepos := line, column, pos
			rune := getRune()
			if !(rune == '_' || unicode.IsLetter(rune) || unicode.IsDigit(rune)) {
				pos = runepos
				current = getc()
				line, column = l, c
				break
			}
		}
		return IDENT
	}
	panic("unreachable")

	goto yyabort // silence unused label error

yyabort: // no lexem recognized
	return unicode.ReplacementChar
}

type visitor struct {
	count    int
	tokCount int
	size     int64
}

func (v *visitor) visitFile(path string) {
	ok, err := filepath.Match("*.go", filepath.Base(path))
	if err != nil {
		panic(err)
	}

	if !ok {
		return
	}

	file, err := os.Open(path)
	if err != nil {
		panic(err)
	}

	defer file.Close()
	src, err = ioutil.ReadAll(file)
	if err != nil {
		panic(err)
	}

	defer func() {
		if e := recover(); e != nil {
			e = fmt.Errorf("%s:%d:%d - scan fail(%s)", path, line, column, e)
			fmt.Println(e)
			os.Exit(1)
		}
	}()

	srclen = len(src)
	pos = 0
	line, column = 1, 1
	current = src[0]
loop:
	for {
		switch x := scan(); {
		default:
			fmt.Println("YO", x)
			v.tokCount++
		case x == 0:
			break loop
		case x == unicode.ReplacementChar:
			break loop
		case x < SEP || x > IMAG:
			panic(fmt.Errorf("%s:%d:%d - scan fail", path, line, column))
		}
	}

	v.count++
	// v.size += f.Size()
}

func main() {

	defer func() {
		if e := recover(); e != nil {
			fmt.Println(e)
			os.Exit(1)
		}
	}()

	v := &visitor{}
	v.visitFile("../main.go")
	// if err := filepath.Walk(runtime.GOROOT()+"/src", func(pth string, info os.FileInfo, err error) error {
	// 	if err != nil {
	// 		return err
	// 	}

	// 	if !info.IsDir() {
	// 		v.visitFile(pth, info)
	// 	}
	// 	return nil
	// }); err != nil {
	// 	panic(err)
	// }

	fmt.Printf("%d .go files, %d bytes, %d tokens\n", v.count, v.size, v.tokCount)
}
